name: example_nav2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  data_api:
    path: external_library/data_api/
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  flutter_lints: ^1.0.4
  flutter_svg:
  flutter_screenutil: ^5.5.3+2
  flutter_gen_runner: ^4.3.0
  intl: ^0.17.0
  flutter_slidable: ^2.0.0
  signature: ^5.1.0
  avoid_keyboard: ^0.3.0
  dropdown_button2: ^1.7.0
  get_cli: ^1.8.1
  flutter_form_builder: ^7.5.0
  image_picker: ^0.8.5+3
  dio: ^4.0.4
  json_serializable: ^6.3.1
  uuid: ^3.0.6
  retrofit: ^3.0.1+1
  collection: ^1.16.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: "^2.1.7"
  #flutter_gen_runner: "4.1.5"
  intl_utils:
  retrofit_generator: any
  

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    package_parameter_enabled: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated/
  use_deferred_loading: false
