name: data_api
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xh_api:
    path: xh_api
  analyzer: ^2.7.0
  dio: ^4.0.4
  openapi_generator_annotations: ^3.3.0
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  openapi_generator: ^3.3.0+1
